// Catan game screen. The client is a dumb projector: it renders the
// server's catan:state (public) + catan:hand (mine) and sends intents.
// All rules run server-side; the candidate targets computed here are a
// UX convenience and the server re-validates everything.
//
// Debug: open game.html?fixture=1 to render a canned mid-game state
// without a server (scripts/catan/fixture.js, regenerated by
// server/tests/make-fixture.mjs).

import { serverURL as server } from "../config.js";
import { createRenderer } from "./render.js";
import { playSound } from "./sounds.js";

const RESOURCES = ["wood", "brick", "sheep", "wheat", "ore"];
const RESOURCE_ICONS = { wood: "🪵", brick: "🧱", sheep: "🐑", wheat: "🌾", ore: "🪨" };
const COSTS = {
  road: { wood: 1, brick: 1 },
  settlement: { wood: 1, brick: 1, sheep: 1, wheat: 1 },
  city: { wheat: 2, ore: 3 },
};

const FIXTURE_MODE = new URLSearchParams(window.location.search).has("fixture");
const roomCode = localStorage.getItem("catanRoomId");

const $ = id => document.getElementById(id);
const els = {
  turnBanner: $("turn-banner"),
  roomChip: $("room-chip"),
  statusStrip: $("status-strip"),
  board: $("board"),
  zoomIn: $("zoom-in"),
  zoomOut: $("zoom-out"),
  zoomReset: $("zoom-reset"),
  players: $("players"),
  die1: $("die-1"),
  die2: $("die-2"),
  rollBtn: $("roll-btn"),
  log: $("log"),
  hand: $("hand"),
  buildRoad: $("build-road"),
  buildSettlement: $("build-settlement"),
  buildCity: $("build-city"),
  tradeBtn: $("trade-btn"),
  endTurn: $("end-turn"),
  discardModal: $("discard-modal"),
  discardPrompt: $("discard-prompt"),
  discardPicker: $("discard-picker"),
  discardConfirm: $("discard-confirm"),
  tradeModal: $("trade-modal"),
  tradeGive: $("trade-give"),
  tradeReceive: $("trade-receive"),
  tradeCancel: $("trade-cancel"),
  tradeConfirm: $("trade-confirm"),
  stealModal: $("steal-modal"),
  stealOptions: $("steal-options"),
  winnerModal: $("winner-modal"),
  winnerTitle: $("winner-title"),
  winnerSub: $("winner-sub"),
};

let pub = null;       // last public state
let mine = null;      // my private view
let mySeat = null;
let renderer = null;
let armedBuild = null;       // 'road' | 'settlement' | 'city' while picking a spot
let pendingRobberHex = null; // chosen hex awaiting victim pick
let soundSeq = null;         // last log seq we've played sounds for

const EVENT_SOUNDS = {
  roll: "roll",
  build: "build",
  placeSettlement: "build",
  placeRoad: "build",
  bankTrade: "trade",
  moveRobber: "robber",
  discard: "discard",
  gameOver: "win",
};

function playLogSounds() {
  if (soundSeq === null) {
    // First snapshot (page load / rejoin): don't replay history.
    soundSeq = pub.seq;
    return;
  }
  for (const e of pub.log) {
    if (e.seq <= soundSeq) continue;
    const fx = EVENT_SOUNDS[e.type];
    if (fx) playSound(fx);
  }
  soundSeq = pub.seq;
}

// ---------------------------------------------------------------------------
// transport
// ---------------------------------------------------------------------------

let socket = null;

function sendIntent(event, payload = {}) {
  if (FIXTURE_MODE) {
    console.log("[fixture] intent:", event, payload);
    return;
  }
  socket.emit(event, { roomCode, ...payload });
}

function connect() {
  socket = io(server, { withCredentials: true });

  const rejoin = () => {
    const seatToken = localStorage.getItem("catanSeatToken");
    socket.emit("catan:rejoin", { roomCode, seatToken }, res => {
      if (!res || !res.ok) {
        showToast(res && res.error ? res.error : "Couldn't join this game.");
        setTimeout(() => { window.location.href = "./home.html"; }, 1800);
        return;
      }
      mySeat = res.seat;
      applyState(res.state, res.hand);
    });
  };

  socket.on("connect", rejoin);
  socket.on("catan:state", state => applyState(state, null));
  socket.on("catan:hand", hand => applyState(null, hand));
  socket.on("catan:error", ({ reason }) => showToast(reason));
}

// ---------------------------------------------------------------------------
// state application
// ---------------------------------------------------------------------------

function applyState(newPub, newMine) {
  if (newPub) {
    if (pub && newPub.seq < pub.seq) return; // stale snapshot
    const firstBoard = !renderer;
    pub = newPub;
    if (firstBoard) {
      renderer = createRenderer(els.board, pub.board, { interactive: true });
      renderer.setHandlers({ onVertex, onEdge, onHex });
      els.zoomIn.addEventListener("click", () => renderer.zoomIn());
      els.zoomOut.addEventListener("click", () => renderer.zoomOut());
      els.zoomReset.addEventListener("click", () => renderer.resetView());
    }
  }
  if (newMine) mine = newMine;
  if (!pub) return;

  if (newPub) playLogSounds();
  renderer.render(pub);
  renderPlayers();
  renderDice();
  renderHand();
  renderLog();
  renderBanner();
  updateButtons();
  updateTargets();
  updateModals();
}

const myTurn = () => mySeat !== null && pub.currentSeat === mySeat;

// ---------------------------------------------------------------------------
// board interactions
// ---------------------------------------------------------------------------

function onVertex(vid) {
  if (pub.phase === "setup") sendIntent("catan:placeSettlement", { vertexId: vid });
  else if (armedBuild === "settlement" || armedBuild === "city") {
    sendIntent("catan:build", { kind: armedBuild, id: vid });
    disarm();
  }
}

function onEdge(eid) {
  if (pub.phase === "setup") sendIntent("catan:placeRoad", { edgeId: eid });
  else if (armedBuild === "road") {
    sendIntent("catan:build", { kind: "road", id: eid });
    disarm();
  }
}

function onHex(hk) {
  if (pub.phase !== "robber" || !myTurn()) return;
  const victims = robberVictimSeats(hk);
  if (victims.length === 0) {
    sendIntent("catan:moveRobber", { hex: hk, victimSeat: null });
  } else if (victims.length === 1) {
    sendIntent("catan:moveRobber", { hex: hk, victimSeat: victims[0] });
  } else {
    pendingRobberHex = hk;
    openStealModal(victims);
  }
}

function disarm() {
  armedBuild = null;
  updateButtons();
  updateTargets();
}

function armBuild(kind) {
  armedBuild = armedBuild === kind ? null : kind;
  updateButtons();
  updateTargets();
}

// ---------------------------------------------------------------------------
// candidate targets (server re-validates; this is just UX)
// ---------------------------------------------------------------------------

function vertexOpen(vid) {
  if (pub.occupied.vertices[vid]) return false;
  return pub.board.vertexAdjacentVertices[vid].every(a => !pub.occupied.vertices[a]);
}

function myRoadTouchesVertex(vid) {
  return pub.board.vertexToEdges[vid].some(e =>
    pub.occupied.edges[e] && pub.occupied.edges[e].seat === mySeat);
}

function legalRoadEdges() {
  return Object.keys(pub.board.edgeToVertices).filter(eid => {
    if (pub.occupied.edges[eid]) return false;
    return pub.board.edgeToVertices[eid].some(vid => {
      const occ = pub.occupied.vertices[vid];
      if (occ && occ.seat === mySeat) return true;
      if (occ && occ.seat !== mySeat) return false;
      return myRoadTouchesVertex(vid);
    });
  });
}

function robberVictimSeats(hk) {
  const seats = new Set();
  for (const vid of pub.board.hexToVertices[hk]) {
    const occ = pub.occupied.vertices[vid];
    if (occ && occ.seat !== mySeat && pub.handCounts[occ.seat] > 0) seats.add(occ.seat);
  }
  return [...seats];
}

function updateTargets() {
  if (!renderer) return;
  renderer.clearTargets();
  if (pub.phase === "finished") return;

  if (pub.phase === "setup") {
    if (pub.setup && mySeat !== null && pub.currentSeat === mySeat) {
      if (pub.setup.expecting === "settlement") {
        renderer.setTargets({ vertices: Object.keys(pub.board.vertexToHexes).filter(vertexOpen) });
      } else {
        renderer.setTargets({
          edges: pub.board.vertexToEdges[pub.setup.lastVertex].filter(e => !pub.occupied.edges[e]),
        });
      }
    }
    return;
  }

  if (pub.phase === "robber" && myTurn()) {
    renderer.setTargets({
      hexes: pub.board.hexes.map(h => `${h.q},${h.r}`).filter(hk => hk !== pub.robberHex),
    });
    return;
  }

  if (pub.phase === "main" && myTurn() && armedBuild) {
    if (armedBuild === "road") {
      renderer.setTargets({ edges: legalRoadEdges() });
    } else if (armedBuild === "settlement") {
      renderer.setTargets({
        vertices: Object.keys(pub.board.vertexToHexes)
          .filter(vid => vertexOpen(vid) && myRoadTouchesVertex(vid)),
      });
    } else if (armedBuild === "city") {
      renderer.setTargets({
        vertices: Object.keys(pub.occupied.vertices).filter(vid => {
          const occ = pub.occupied.vertices[vid];
          return occ.seat === mySeat && occ.type === "settlement";
        }),
      });
    }
  }
}

// ---------------------------------------------------------------------------
// panels / dock rendering
// ---------------------------------------------------------------------------

function renderPlayers() {
  els.players.innerHTML = "";
  pub.seats.forEach((seat, i) => {
    const panel = document.createElement("div");
    panel.className = "player-panel" + (i === pub.currentSeat ? " current-turn" : "");
    const dis = seat.connected ? "" : '<span class="disconnected-badge">OFFLINE</span>';
    const you = i === mySeat ? " (you)" : "";
    panel.innerHTML = `
      <div class="player-swatch" style="background:${seat.colour}"></div>
      <div class="player-name">${escapeHtml(seat.name)}${you}${dis}</div>
      <div class="player-stats">
        <span class="stat-vp">★ ${pub.vp[i]}</span>
        <span>🎴 ${pub.handCounts[i]}</span>
      </div>`;
    els.players.appendChild(panel);
  });
}

const PIP_LAYOUT = {
  1: [4], 2: [0, 8], 3: [0, 4, 8], 4: [0, 2, 6, 8], 5: [0, 2, 4, 6, 8], 6: [0, 2, 3, 5, 6, 8],
};

function renderDie(el, value) {
  el.innerHTML = "";
  if (!value) return;
  const cells = PIP_LAYOUT[value] || [];
  for (let i = 0; i < 9; i++) {
    const cell = document.createElement("div");
    if (cells.includes(i)) cell.className = "pip";
    el.appendChild(cell);
  }
}

function renderDice() {
  renderDie(els.die1, pub.dice && pub.dice.d1);
  renderDie(els.die2, pub.dice && pub.dice.d2);
}

function renderHand() {
  els.hand.innerHTML = "";
  if (!mine) return;
  for (const res of RESOURCES) {
    const n = mine.hand[res];
    if (!n) continue;
    const card = document.createElement("div");
    card.className = `card card-${res}`;
    card.title = res;
    card.innerHTML = `<span>${RESOURCE_ICONS[res]}</span><span class="card-count">×${n}</span>`;
    els.hand.appendChild(card);
  }
  if (!els.hand.children.length) {
    els.hand.innerHTML = '<span style="color:#FFF;opacity:.7;font-weight:700">No cards yet</span>';
  }
}

function seatName(i) {
  return pub.seats[i] ? pub.seats[i].name : `Player ${i}`;
}

function describeLogEntry(e) {
  switch (e.type) {
    case "roll": return `<b>${escapeHtml(seatName(e.seat))}</b> rolled <b>${e.total}</b>`;
    case "production": {
      const parts = [];
      for (const s in e.gains) {
        const items = Object.entries(e.gains[s]).map(([r, n]) => `${n}${RESOURCE_ICONS[r]}`).join(" ");
        parts.push(`${escapeHtml(seatName(+s))} +${items}`);
      }
      return parts.length ? parts.join(", ") : "no production";
    }
    case "placeSettlement": return `<b>${escapeHtml(seatName(e.seat))}</b> placed a settlement`;
    case "placeRoad": return `<b>${escapeHtml(seatName(e.seat))}</b> placed a road`;
    case "setupGrant": return null;
    case "setupComplete": return "Setup complete — game on!";
    case "build": return `<b>${escapeHtml(seatName(e.seat))}</b> built a ${e.kind}`;
    case "bankTrade": return `<b>${escapeHtml(seatName(e.seat))}</b> traded 4 ${RESOURCE_ICONS[e.give]} → 1 ${RESOURCE_ICONS[e.receive]}`;
    case "discard": return `<b>${escapeHtml(seatName(e.seat))}</b> discarded ${e.count} cards`;
    case "discardPhase": return "Over 7 cards — discard time!";
    case "robberPhase": return null;
    case "moveRobber": return `<b>${escapeHtml(seatName(e.seat))}</b> moved the robber`;
    case "steal": return `<b>${escapeHtml(seatName(e.seat))}</b> stole a card from <b>${escapeHtml(seatName(e.victim))}</b>`;
    case "endTurn": return null;
    case "gameOver": return `<b>${escapeHtml(seatName(e.seat))}</b> wins!`;
    default: return null;
  }
}

function renderLog() {
  const lines = [];
  for (const e of pub.log) {
    const text = describeLogEntry(e);
    if (text) lines.push(`<p class="log-entry">${text}</p>`);
  }
  els.log.innerHTML = lines.join("");
  els.log.scrollTop = els.log.scrollHeight;
}

function renderBanner() {
  els.roomChip.textContent = FIXTURE_MODE ? "FIXTURE" : `ROOM ${roomCode || "?"}`;
  const name = seatName(pub.currentSeat);
  let phaseText = "";
  let status = "";

  if (pub.phase === "setup") {
    phaseText = `${name} is placing`;
    if (mySeat !== null && pub.currentSeat === mySeat && pub.setup) {
      status = pub.setup.expecting === "settlement"
        ? "Place a settlement on any highlighted corner"
        : "Place a road next to your new settlement";
    }
  } else if (pub.phase === "roll") {
    phaseText = `${name}'s turn`;
    if (myTurn()) status = "Roll the dice!";
  } else if (pub.phase === "discard") {
    phaseText = "Waiting for discards…";
  } else if (pub.phase === "robber") {
    phaseText = `${name} is moving the robber`;
    if (myTurn()) status = "Pick a hex for the robber";
  } else if (pub.phase === "main") {
    phaseText = `${name}'s turn`;
    if (myTurn()) {
      status = armedBuild ? `Pick a spot for your ${armedBuild}` : "Build, trade, or end your turn";
    }
  } else if (pub.phase === "finished") {
    phaseText = `${seatName(pub.winner)} wins!`;
  }

  els.turnBanner.textContent = phaseText;
  els.statusStrip.textContent = status;
}

function canAfford(kind) {
  if (!mine) return false;
  return Object.entries(COSTS[kind]).every(([res, n]) => mine.hand[res] >= n);
}

function updateButtons() {
  const main = pub.phase === "main" && myTurn();
  els.rollBtn.disabled = !(pub.phase === "roll" && myTurn());
  els.buildRoad.disabled = !(main && canAfford("road") && pub.pieces[mySeat].roads > 0);
  els.buildSettlement.disabled = !(main && canAfford("settlement") && pub.pieces[mySeat].settlements > 0);
  els.buildCity.disabled = !(main && canAfford("city") && pub.pieces[mySeat].cities > 0);
  els.tradeBtn.disabled = !(main && mine && RESOURCES.some(r => mine.hand[r] >= 4));
  els.endTurn.disabled = !main;

  for (const [btn, kind] of [[els.buildRoad, "road"], [els.buildSettlement, "settlement"], [els.buildCity, "city"]]) {
    btn.classList.toggle("armed", armedBuild === kind);
  }
}

// ---------------------------------------------------------------------------
// modals
// ---------------------------------------------------------------------------

function buildPicker(container, counts, max, onChange) {
  container.innerHTML = "";
  const picked = {};
  for (const res of RESOURCES) {
    picked[res] = 0;
    const cell = document.createElement("div");
    cell.className = "picker-cell";
    cell.innerHTML = `
      <div class="card card-${res}" style="width:38px;height:50px;font-size:1rem">${RESOURCE_ICONS[res]}</div>
      <span class="count" data-res="${res}">0</span>
      <div class="mini-btns">
        <button type="button" data-res="${res}" data-d="-1">−</button>
        <button type="button" data-res="${res}" data-d="1">+</button>
      </div>`;
    container.appendChild(cell);
  }
  container.onclick = (e) => {
    const btn = e.target.closest("button");
    if (!btn) return;
    const res = btn.getAttribute("data-res");
    const d = parseInt(btn.getAttribute("data-d"), 10);
    const total = Object.values(picked).reduce((a, b) => a + b, 0);
    if (d > 0 && (picked[res] >= counts[res] || total >= max)) return;
    if (d < 0 && picked[res] <= 0) return;
    picked[res] += d;
    container.querySelector(`.count[data-res="${res}"]`).textContent = picked[res];
    onChange(picked);
  };
  return picked;
}

function updateModals() {
  // Discard modal: shown when I owe cards.
  const owe = mine ? mine.discardPending : 0;
  if (pub.phase === "discard" && owe > 0) {
    if (els.discardModal.hidden) openDiscardModal(owe);
  } else {
    els.discardModal.hidden = true;
  }

  if (pub.phase !== "robber") {
    els.stealModal.hidden = true;
    pendingRobberHex = null;
  }

  if (pub.phase === "finished" && pub.winner !== null) {
    els.winnerTitle.textContent = `${seatName(pub.winner)} wins! 🏆`;
    els.winnerSub.textContent = pub.winner === mySeat
      ? "Congratulations, you settled Catan."
      : "Better luck next game.";
    els.winnerModal.hidden = false;
  }
}

function openDiscardModal(owe) {
  els.discardPrompt.textContent = `You have more than 7 cards — discard ${owe}.`;
  let current = {};
  buildPicker(els.discardPicker, mine.hand, owe, picked => {
    current = picked;
    const total = Object.values(picked).reduce((a, b) => a + b, 0);
    els.discardConfirm.disabled = total !== owe;
  });
  els.discardConfirm.disabled = true;
  els.discardConfirm.onclick = () => {
    sendIntent("catan:discard", { resources: current });
    els.discardModal.hidden = true;
  };
  els.discardModal.hidden = false;
}

function openTradeModal() {
  let give = null, receive = null;
  const renderRow = (container, label, eligible, onPick, selected) => {
    container.innerHTML = `<span style="align-self:center;font-weight:800">${label}</span>`;
    for (const res of RESOURCES) {
      const card = document.createElement("div");
      card.className = `card card-${res}`;
      card.style.cssText = "width:38px;height:50px;font-size:1rem;cursor:pointer";
      if (!eligible(res)) card.style.opacity = "0.3";
      if (selected === res) card.style.outline = "3px solid var(--c-accent)";
      card.innerHTML = `<span>${RESOURCE_ICONS[res]}</span>`;
      card.onclick = () => { if (eligible(res)) onPick(res); };
      container.appendChild(card);
    }
  };
  const refresh = () => {
    renderRow(els.tradeGive, "Give 4", r => mine.hand[r] >= 4 && r !== receive, r => { give = r; refresh(); }, give);
    renderRow(els.tradeReceive, "Get 1", r => r !== give, r => { receive = r; refresh(); }, receive);
    els.tradeConfirm.disabled = !(give && receive);
  };
  refresh();
  els.tradeConfirm.onclick = () => {
    sendIntent("catan:bankTrade", { give, receive });
    els.tradeModal.hidden = true;
  };
  els.tradeCancel.onclick = () => { els.tradeModal.hidden = true; };
  els.tradeModal.hidden = false;
}

function openStealModal(victims) {
  els.stealOptions.innerHTML = "";
  for (const v of victims) {
    const btn = document.createElement("button");
    btn.className = "catan-btn";
    btn.innerHTML = `<span class="player-swatch" style="display:inline-block;background:${pub.seats[v].colour}"></span> ${escapeHtml(seatName(v))} (${pub.handCounts[v]} cards)`;
    btn.onclick = () => {
      sendIntent("catan:moveRobber", { hex: pendingRobberHex, victimSeat: v });
      els.stealModal.hidden = true;
      pendingRobberHex = null;
    };
    els.stealOptions.appendChild(btn);
  }
  els.stealModal.hidden = false;
}

// ---------------------------------------------------------------------------
// misc
// ---------------------------------------------------------------------------

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, c => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  }[c]));
}

let toastTimer = null;
function showToast(message) {
  els.statusStrip.textContent = message;
  els.statusStrip.style.background = "var(--c-highlight)";
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => {
    els.statusStrip.style.background = "";
    renderBanner();
  }, 2500);
}

// ---------------------------------------------------------------------------
// wire buttons + boot
// ---------------------------------------------------------------------------

els.rollBtn.addEventListener("click", () => sendIntent("catan:roll"));
els.endTurn.addEventListener("click", () => { disarm(); sendIntent("catan:endTurn"); });
els.buildRoad.addEventListener("click", () => armBuild("road"));
els.buildSettlement.addEventListener("click", () => armBuild("settlement"));
els.buildCity.addEventListener("click", () => armBuild("city"));
els.tradeBtn.addEventListener("click", openTradeModal);

if (FIXTURE_MODE) {
  import("./fixture.js").then(({ fixturePublic, fixturePrivate }) => {
    mySeat = fixturePrivate.seat;
    applyState(fixturePublic, fixturePrivate);
  });
} else if (!roomCode) {
  window.location.href = "./home.html";
} else {
  connect();
}
