// Catan game screen. The client is a dumb projector: it renders the
// server's catan:state (public) + catan:hand (mine) and sends intents.
// All rules run server-side; the candidate targets computed here are a
// UX convenience and the server re-validates everything.
//
// Debug: open game.html?fixture=1 to render a canned mid-game state
// without a server (scripts/catan/fixture.js, regenerated by
// server/tests/make-fixture.mjs).

import { serverURL as server } from "../config.js";
import { createRenderer } from "./render.js";
import { playSound, isMuted, setMuted } from "./sounds.js";
import { trapFocus } from "../modal-behavior.js";
import { attachConnectionBanner } from "../connection.js";

const RESOURCES = ["wood", "brick", "sheep", "wheat", "ore"];
const RESOURCE_ICONS = { wood: "🪵", brick: "🧱", sheep: "🐑", wheat: "🌾", ore: "🪨" };
const COSTS = {
  road: { wood: 1, brick: 1 },
  settlement: { wood: 1, brick: 1, sheep: 1, wheat: 1 },
  city: { wheat: 2, ore: 3 },
};

const FIXTURE_MODE = new URLSearchParams(window.location.search).has("fixture");
const roomCode = localStorage.getItem("catanRoomId");

const $ = id => document.getElementById(id);
const els = {
  turnBanner: $("turn-banner"),
  roomChip: $("room-chip"),
  statusStrip: $("status-strip"),
  board: $("board"),
  zoomIn: $("zoom-in"),
  zoomOut: $("zoom-out"),
  zoomReset: $("zoom-reset"),
  players: $("players"),
  die1: $("die-1"),
  die2: $("die-2"),
  diceTray: $("dice-tray"),
  dicePair: $("dice-pair"),
  diceHint: $("dice-hint"),
  turnTimer: $("turn-timer"),
  soundToggle: $("sound-toggle"),
  bankRow: $("bank-row"),
  log: $("log"),
  hand: $("hand"),
  devHand: $("dev-hand"),
  buildRoad: $("build-road"),
  buildSettlement: $("build-settlement"),
  buildCity: $("build-city"),
  buyDev: $("buy-dev"),
  tradeBank: $("trade-bank"),
  tradePlayers: $("trade-players"),
  endTurn: $("end-turn"),
  offerModal: $("offer-modal"),
  offerGive: $("offer-give"),
  offerGet: $("offer-get"),
  offerTarget: $("offer-target"),
  offerCancel: $("offer-cancel"),
  offerSend: $("offer-send"),
  incomingModal: $("incoming-modal"),
  incomingTitle: $("incoming-title"),
  incomingBody: $("incoming-body"),
  incomingActions: $("incoming-actions"),
  incomingAccept: $("incoming-accept"),
  incomingDecline: $("incoming-decline"),
  resourceModal: $("resource-modal"),
  resourceTitle: $("resource-title"),
  resourcePrompt: $("resource-prompt"),
  resourcePicker: $("resource-picker"),
  resourceCancel: $("resource-cancel"),
  resourceConfirm: $("resource-confirm"),
  winnerScores: $("winner-scores"),
  discardModal: $("discard-modal"),
  discardPrompt: $("discard-prompt"),
  discardPicker: $("discard-picker"),
  discardConfirm: $("discard-confirm"),
  tradeModal: $("trade-modal"),
  tradeGive: $("trade-give"),
  tradeReceive: $("trade-receive"),
  tradeCancel: $("trade-cancel"),
  tradeConfirm: $("trade-confirm"),
  stealModal: $("steal-modal"),
  stealOptions: $("steal-options"),
  winnerModal: $("winner-modal"),
  winnerTitle: $("winner-title"),
  winnerSub: $("winner-sub"),
};

// ---------------------------------------------------------------------------
// accessible modal helpers
// ---------------------------------------------------------------------------

let currentModalEl = null;
let releaseModal = null;
function openModal(el, { dismissable = true, onDismiss } = {}) {
  // Catan shows one modal at a time; close any currently-open one first so
  // its focus trap is released (prevents a leaked keydown listener).
  if (currentModalEl && currentModalEl !== el) closeModal(currentModalEl);
  el.hidden = false;
  currentModalEl = el;
  releaseModal = trapFocus(el, dismissable ? { onEscape: () => { closeModal(el); if (onDismiss) onDismiss(); } } : {});
}
function closeModal(el) {
  el.hidden = true;
  if (currentModalEl === el) {
    if (releaseModal) { releaseModal(); releaseModal = null; }
    currentModalEl = null;
  }
}

let pub = null;       // last public state
let mine = null;      // my private view
let mySeat = null;
let renderer = null;
let armedBuild = null;       // 'road' | 'settlement' | 'city' while picking a spot
let pendingRobberHex = null; // chosen hex awaiting victim pick
let knightPending = false;   // playing a Knight: next hex click steals via the card
let devRoadEdges = null;     // array while placing Road Building's free roads
let soundSeq = null;         // last log seq we've played sounds for
let timerTick = null;        // interval id for the turn-timer countdown
let dismissedTradeKey = null; // signature of the last incoming offer we declined

const REDUCED_MOTION = window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;
let prevHand = null;      // hand before the latest catan:hand, for delta chips
let diceAnimating = false;

const RESOURCE_NAMES = { wood: "wood", brick: "brick", sheep: "sheep", wheat: "wheat", ore: "ore" };

// Per-event sound choice; null = silent.
function soundForEvent(e) {
  switch (e.type) {
    case "roll": return "roll";
    case "placeRoad": return "road";
    case "placeSettlement": return "settlement";
    case "build": return e.kind === "city" ? "city" : e.kind === "settlement" ? "settlement" : "road";
    case "bankTrade":
    case "tradeAccepted": return "trade";
    case "tradeOffer": return "tradeOffer";
    case "buyDev": return "buyDev";
    case "playDev": return e.card === "knight" ? "knight" : "playDev";
    case "moveRobber": return "robber";
    case "steal": return "steal";
    case "discard": return "discard";
    case "production":
      return mySeat !== null && e.gains[mySeat] && Object.keys(e.gains[mySeat]).length ? "gain" : null;
    case "longestRoad":
    case "largestArmy": return e.seat === null ? null : "award";
    case "gameOver": return e.seat === mySeat ? "winMe" : "winOther";
    default: return null;
  }
}

// Visual cues driven by the same log diff as sounds (Task 7 adds banners).
function animateForEvent(e) {
  if (e.type === "roll") animateDiceRoll();
}

function processLogEvents() {
  if (soundSeq === null) {
    // First snapshot (page load / rejoin): don't replay history.
    soundSeq = pub.seq;
    return;
  }
  for (const e of pub.log) {
    if (e.seq <= soundSeq) continue;
    const fx = soundForEvent(e);
    if (fx) playSound(fx);
    animateForEvent(e);
  }
  soundSeq = pub.seq;
}

// ---------------------------------------------------------------------------
// transport
// ---------------------------------------------------------------------------

let socket = null;

function sendIntent(event, payload = {}) {
  if (FIXTURE_MODE) {
    console.log("[fixture] intent:", event, payload);
    return;
  }
  socket.emit(event, { roomCode, ...payload });
}

function connect() {
  socket = io(server, { withCredentials: true });
  attachConnectionBanner(socket);

  const rejoin = () => {
    const seatToken = localStorage.getItem("catanSeatToken");
    socket.emit("catan:rejoin", { roomCode, seatToken }, res => {
      if (!res || !res.ok) {
        showToast(res && res.error ? res.error : "Couldn't join this game.");
        setTimeout(() => { window.location.href = "./home.html"; }, 1800);
        return;
      }
      mySeat = res.seat;
      applyState(res.state, res.hand);
    });
  };

  socket.on("connect", rejoin);
  socket.on("catan:state", state => applyState(state, null));
  socket.on("catan:hand", hand => applyState(null, hand));
  socket.on("catan:error", ({ reason }) => showToast(reason));
  socket.on("catan:tradeDeclined", ({ seat }) => {
    if (pub && pub.trade && pub.trade.from === mySeat) showToast(`${seatName(seat)} declined your offer`);
  });
}

// ---------------------------------------------------------------------------
// state application
// ---------------------------------------------------------------------------

function applyState(newPub, newMine) {
  if (newPub) {
    if (pub && newPub.seq < pub.seq) return; // stale snapshot
    const firstBoard = !renderer;
    pub = newPub;
    if (firstBoard) {
      renderer = createRenderer(els.board, pub.board, { interactive: true });
      renderer.setHandlers({ onVertex, onEdge, onHex });
      els.zoomIn.addEventListener("click", () => renderer.zoomIn());
      els.zoomOut.addEventListener("click", () => renderer.zoomOut());
      els.zoomReset.addEventListener("click", () => renderer.resetView());
    }
  }
  if (newMine) {
    prevHand = mine && mine.hand;
    mine = newMine;
  }
  if (!pub) return;

  if (newPub) processLogEvents();
  if (newPub) renderer.render(pub);
  renderPlayers();
  renderDice();
  renderBank();
  renderHand();
  renderDevHand();
  renderLog();
  renderBanner();
  renderTimer();
  updateButtons();
  updateTargets();
  updateModals();
  updateIncomingTrade();
}

// ---------------------------------------------------------------------------
// turn timer countdown
// ---------------------------------------------------------------------------

function renderTimer() {
  if (timerTick) { clearInterval(timerTick); timerTick = null; }
  if (!pub.turnDeadline || pub.phase === "finished") {
    els.turnTimer.hidden = true;
    return;
  }
  const tick = () => {
    const left = Math.max(0, Math.round((pub.turnDeadline - Date.now()) / 1000));
    els.turnTimer.hidden = false;
    els.turnTimer.textContent = `⏱ ${left}s`;
    els.turnTimer.classList.toggle("urgent", left <= 10);
    if (left <= 0 && timerTick) { clearInterval(timerTick); timerTick = null; }
  };
  tick();
  timerTick = setInterval(tick, 500);
}

const myTurn = () => mySeat !== null && pub.currentSeat === mySeat;

// ---------------------------------------------------------------------------
// board interactions
// ---------------------------------------------------------------------------

function onVertex(vid) {
  if (pub.phase === "setup") sendIntent("catan:placeSettlement", { vertexId: vid });
  else if (armedBuild === "settlement" || armedBuild === "city") {
    sendIntent("catan:build", { kind: armedBuild, id: vid });
    disarm();
  }
}

function onEdge(eid) {
  if (pub.phase === "setup") { sendIntent("catan:placeRoad", { edgeId: eid }); return; }
  if (devRoadEdges) {
    devRoadEdges.push(eid);
    if (devRoadEdges.length === 2 || legalRoadEdges(devRoadEdges).length === 0) {
      sendIntent("catan:playRoadBuilding", { edge1: devRoadEdges[0], edge2: devRoadEdges[1] || null });
      devRoadEdges = null;
      updateTargets();
    } else {
      updateTargets(); // highlight the remaining legal edges (incl. ones reached by edge 1)
    }
    return;
  }
  if (armedBuild === "road") {
    sendIntent("catan:build", { kind: "road", id: eid });
    disarm();
  }
}

// hex clicks drive both the rolled-7 robber and a played Knight card.
function onHex(hk) {
  const isRobber = pub.phase === "robber" && myTurn();
  if (!isRobber && !knightPending) return;
  const event = knightPending ? "catan:playKnight" : "catan:moveRobber";
  const victims = robberVictimSeats(hk);
  if (victims.length === 0) {
    sendIntent(event, { hex: hk, victimSeat: null });
    knightPending = false;
  } else if (victims.length === 1) {
    sendIntent(event, { hex: hk, victimSeat: victims[0] });
    knightPending = false;
  } else {
    pendingRobberHex = hk;
    openStealModal(victims, event);
  }
}

function disarm() {
  armedBuild = null;
  knightPending = false;
  devRoadEdges = null;
  updateButtons();
  updateTargets();
}

function armBuild(kind) {
  const next = armedBuild === kind ? null : kind;
  armedBuild = next;
  knightPending = false;
  devRoadEdges = null;
  updateButtons();
  updateTargets();
}

// ---------------------------------------------------------------------------
// candidate targets (server re-validates; this is just UX)
// ---------------------------------------------------------------------------

function vertexOpen(vid) {
  if (pub.occupied.vertices[vid]) return false;
  return pub.board.vertexAdjacentVertices[vid].every(a => !pub.occupied.vertices[a]);
}

function myRoadTouchesVertex(vid) {
  return pub.board.vertexToEdges[vid].some(e =>
    pub.occupied.edges[e] && pub.occupied.edges[e].seat === mySeat);
}

// Legal road edges for mySeat. `extra` is a list of not-yet-committed edges
// (Road Building's first pick) treated as already owned so the second pick
// can chain off it.
function legalRoadEdges(extra = []) {
  const owns = eid => (pub.occupied.edges[eid] && pub.occupied.edges[eid].seat === mySeat) || extra.includes(eid);
  return Object.keys(pub.board.edgeToVertices).filter(eid => {
    if (pub.occupied.edges[eid] || extra.includes(eid)) return false;
    return pub.board.edgeToVertices[eid].some(vid => {
      const occ = pub.occupied.vertices[vid];
      if (occ && occ.seat === mySeat) return true;
      if (occ && occ.seat !== mySeat) return false;
      return pub.board.vertexToEdges[vid].some(owns);
    });
  });
}

function robberVictimSeats(hk) {
  const seats = new Set();
  for (const vid of pub.board.hexToVertices[hk]) {
    const occ = pub.occupied.vertices[vid];
    if (occ && occ.seat !== mySeat && pub.handCounts[occ.seat] > 0) seats.add(occ.seat);
  }
  return [...seats];
}

function updateTargets() {
  if (!renderer) return;
  renderer.clearTargets();
  if (pub.phase === "finished") return;

  if (pub.phase === "setup") {
    if (pub.setup && mySeat !== null && pub.currentSeat === mySeat) {
      if (pub.setup.expecting === "settlement") {
        renderer.setTargets({ vertices: Object.keys(pub.board.vertexToHexes).filter(vertexOpen) });
      } else {
        renderer.setTargets({
          edges: pub.board.vertexToEdges[pub.setup.lastVertex].filter(e => !pub.occupied.edges[e]),
        });
      }
    }
    return;
  }

  if ((pub.phase === "robber" && myTurn()) || knightPending) {
    renderer.setTargets({
      hexes: pub.board.hexes.map(h => `${h.q},${h.r}`).filter(hk => hk !== pub.robberHex),
    });
    return;
  }

  if (devRoadEdges) {
    renderer.setTargets({ edges: legalRoadEdges(devRoadEdges) });
    return;
  }

  if (pub.phase === "main" && myTurn() && armedBuild) {
    if (armedBuild === "road") {
      renderer.setTargets({ edges: legalRoadEdges() });
    } else if (armedBuild === "settlement") {
      renderer.setTargets({
        vertices: Object.keys(pub.board.vertexToHexes)
          .filter(vid => vertexOpen(vid) && myRoadTouchesVertex(vid)),
      });
    } else if (armedBuild === "city") {
      renderer.setTargets({
        vertices: Object.keys(pub.occupied.vertices).filter(vid => {
          const occ = pub.occupied.vertices[vid];
          return occ.seat === mySeat && occ.type === "settlement";
        }),
      });
    }
  }
}

// ---------------------------------------------------------------------------
// panels / dock rendering
// ---------------------------------------------------------------------------

function renderPlayers() {
  els.players.innerHTML = "";
  pub.seats.forEach((seat, i) => {
    const panel = document.createElement("div");
    panel.className = "player-panel" + (i === pub.currentSeat ? " current-turn" : "");
    const dis = seat.connected ? "" : '<span class="disconnected-badge">OFFLINE</span>';
    const you = i === mySeat ? " (you)" : "";
    const badges =
      (pub.longestRoad === i ? `<span class="award" title="Longest Road (${pub.longestRoadLen})">🛣️</span>` : "") +
      (pub.largestArmy === i ? `<span class="award" title="Largest Army (${pub.knightsPlayed[i]} knights)">⚔️</span>` : "");
    const devN = pub.devCounts[i] || 0;
    const roadLen = (pub.roadLengths && pub.roadLengths[i]) || 0;
    const holdsRoad = pub.longestRoad === i;
    panel.innerHTML = `
      <div class="player-swatch" style="background:${seat.colour}"></div>
      <div class="player-name">${escapeHtml(seat.name)}${you}${dis} ${badges}</div>
      <div class="player-stats">
        <span class="stat-vp">★ ${pub.vp[i]}</span>
        <span title="resource cards">🎴 ${pub.handCounts[i]}</span>
        <span title="development cards">🃏 ${devN}</span>
        <span class="stat-road${holdsRoad ? " lr-holder" : ""}" title="longest road${holdsRoad ? " — holds the bonus" : ""}">🛣️ ${roadLen}</span>
      </div>`;
    els.players.appendChild(panel);
  });
}

const BANK_ORDER = ["wood", "brick", "sheep", "wheat", "ore"];

function renderBank() {
  els.bankRow.innerHTML = "";
  for (const res of BANK_ORDER) {
    const cell = document.createElement("div");
    cell.className = "bank-cell";
    cell.innerHTML = `<span class="bank-icon">${RESOURCE_ICONS[res]}</span><span class="bank-count">${pub.bank[res]}</span>`;
    els.bankRow.appendChild(cell);
  }
}

const DEV_LABELS = {
  knight: { icon: "⚔️", name: "Knight" },
  road: { icon: "🛣️", name: "Road Building" },
  plenty: { icon: "🌾", name: "Year of Plenty" },
  monopoly: { icon: "💰", name: "Monopoly" },
  vp: { icon: "⭐", name: "Victory Point" },
};

function renderDevHand() {
  els.devHand.innerHTML = "";
  if (!mine) return;
  const canPlay = pub.phase === "main" && myTurn();
  let any = false;
  for (const card of ["knight", "road", "plenty", "monopoly", "vp"]) {
    const playable = mine.dev[card] || 0;
    const fresh = mine.devNew[card] || 0;
    const total = playable + fresh;
    if (total === 0) continue;
    any = true;
    const meta = DEV_LABELS[card];
    const chip = document.createElement("button");
    chip.className = "dev-chip";
    // Knights may also be played in the roll phase.
    const usable = card !== "vp" && playable > 0 &&
      (canPlay || (card === "knight" && pub.phase === "roll" && myTurn()));
    chip.disabled = !usable;
    chip.innerHTML = `<span class="dev-ic">${meta.icon}</span><span class="dev-nm">${meta.name}</span><span class="dev-ct">×${total}</span>` +
      (fresh > 0 ? `<span class="dev-new" title="bought this turn — playable next turn">🔒${fresh}</span>` : "");
    if (usable) chip.addEventListener("click", () => playDevCard(card));
    els.devHand.appendChild(chip);
  }
  els.devHand.style.display = any ? "" : "none";
}

const PIP_LAYOUT = {
  1: [4], 2: [0, 8], 3: [0, 4, 8], 4: [0, 2, 6, 8], 5: [0, 2, 4, 6, 8], 6: [0, 2, 3, 5, 6, 8],
};

function renderDie(el, value) {
  el.innerHTML = "";
  if (!value) return;
  const cells = PIP_LAYOUT[value] || [];
  for (let i = 0; i < 9; i++) {
    const cell = document.createElement("div");
    if (cells.includes(i)) cell.className = "pip";
    el.appendChild(cell);
  }
}

function renderDice() {
  if (diceAnimating) return;
  renderDie(els.die1, pub.dice && pub.dice.d1);
  renderDie(els.die2, pub.dice && pub.dice.d2);
}

function animateDiceRoll() {
  if (diceAnimating || REDUCED_MOTION) return;
  diceAnimating = true;
  els.dicePair.classList.add("tumbling");
  const iv = setInterval(() => {
    renderDie(els.die1, 1 + Math.floor(Math.random() * 6));
    renderDie(els.die2, 1 + Math.floor(Math.random() * 6));
  }, 80);
  setTimeout(() => {
    clearInterval(iv);
    diceAnimating = false;
    els.dicePair.classList.remove("tumbling");
    renderDice();
    els.dicePair.classList.add("settled");
    setTimeout(() => els.dicePair.classList.remove("settled"), 320);
  }, 420);
}

// Deltas since the previous hand snapshot; consumed on render so pub-only
// re-renders don't replay the chips.
function takeHandDeltas() {
  if (!mine || !prevHand) return {};
  const out = {};
  for (const res of RESOURCES) {
    const d = (mine.hand[res] || 0) - (prevHand[res] || 0);
    if (d) out[res] = d;
  }
  prevHand = null;
  return out;
}

function renderHand() {
  const deltas = REDUCED_MOTION ? {} : takeHandDeltas();
  els.hand.innerHTML = "";
  if (!mine) return;
  for (const res of RESOURCES) {
    const n = mine.hand[res];
    if (!n) continue;
    const card = document.createElement("div");
    card.className = `card card-${res}`;
    card.title = res;
    card.innerHTML = `<span>${RESOURCE_ICONS[res]}</span><span class="card-count">×${n}</span>`;
    if (deltas[res]) {
      card.classList.add("bump");
      const chip = document.createElement("span");
      chip.className = `delta-chip ${deltas[res] > 0 ? "plus" : "minus"}`;
      chip.textContent = `${deltas[res] > 0 ? "+" : ""}${deltas[res]}`;
      chip.addEventListener("animationend", () => chip.remove());
      card.appendChild(chip);
    }
    els.hand.appendChild(card);
  }
  if (!els.hand.children.length) {
    els.hand.innerHTML = '<span style="color:#FFF;opacity:.7;font-weight:700">No cards yet</span>';
  }
}

function seatName(i) {
  return pub.seats[i] ? pub.seats[i].name : `Player ${i}`;
}

function describeLogEntry(e) {
  switch (e.type) {
    case "roll": return `<b>${escapeHtml(seatName(e.seat))}</b> rolled <b>${e.total}</b>`;
    case "production": {
      const parts = [];
      for (const s in e.gains) {
        const items = Object.entries(e.gains[s]).map(([r, n]) => `${n}${RESOURCE_ICONS[r]}`).join(" ");
        parts.push(`${escapeHtml(seatName(+s))} +${items}`);
      }
      return parts.length ? parts.join(", ") : "no production";
    }
    case "placeSettlement": return `<b>${escapeHtml(seatName(e.seat))}</b> placed a settlement`;
    case "placeRoad": return `<b>${escapeHtml(seatName(e.seat))}</b> placed a road`;
    case "setupGrant": return null;
    case "setupComplete": return "Setup complete — game on!";
    case "build": return `<b>${escapeHtml(seatName(e.seat))}</b> built a ${e.kind}`;
    case "bankTrade": return `<b>${escapeHtml(seatName(e.seat))}</b> traded ${e.rate} ${RESOURCE_ICONS[e.give]} → 1 ${RESOURCE_ICONS[e.receive]}`;
    case "discard": return `<b>${escapeHtml(seatName(e.seat))}</b> discarded ${e.count} cards`;
    case "discardPhase": return "Over 7 cards — discard time!";
    case "robberPhase": return null;
    case "moveRobber": return `<b>${escapeHtml(seatName(e.seat))}</b> moved the robber`;
    case "steal": return `<b>${escapeHtml(seatName(e.seat))}</b> stole a card from <b>${escapeHtml(seatName(e.victim))}</b>`;
    case "buyDev": return `<b>${escapeHtml(seatName(e.seat))}</b> bought a development card`;
    case "playDev": {
      const names = { knight: "a Knight", road: "Road Building", plenty: "Year of Plenty", monopoly: "Monopoly" };
      return `<b>${escapeHtml(seatName(e.seat))}</b> played ${names[e.card] || "a card"}`;
    }
    case "tradeOffer": return `<b>${escapeHtml(seatName(e.seat))}</b> offered a trade`;
    case "tradeAccepted": return `<b>${escapeHtml(seatName(e.by))}</b> traded with <b>${escapeHtml(seatName(e.from))}</b>`;
    case "tradeCancelled": return null;
    case "longestRoad": return `<b>${escapeHtml(seatName(e.seat))}</b> took Longest Road (${e.length})`;
    case "largestArmy": return `<b>${escapeHtml(seatName(e.seat))}</b> took Largest Army (${e.knights})`;
    case "endTurn": return null;
    case "gameOver": return `<b>${escapeHtml(seatName(e.seat))}</b> wins!`;
    default: return null;
  }
}

function renderLog() {
  const lines = [];
  for (const e of pub.log) {
    const text = describeLogEntry(e);
    if (text) lines.push(`<p class="log-entry">${text}</p>`);
  }
  els.log.innerHTML = lines.join("");
  els.log.scrollTop = els.log.scrollHeight;
}

function renderBanner() {
  els.roomChip.textContent = FIXTURE_MODE ? "FIXTURE" : `ROOM ${roomCode || "?"}`;
  const name = seatName(pub.currentSeat);
  let phaseText = "";
  let status = "";

  if (pub.phase === "setup") {
    phaseText = `${name} is placing`;
    if (mySeat !== null && pub.currentSeat === mySeat && pub.setup) {
      status = pub.setup.expecting === "settlement"
        ? "Place a settlement on any highlighted corner"
        : "Place a road next to your new settlement";
    }
  } else if (pub.phase === "roll") {
    phaseText = `${name}'s turn`;
    if (myTurn()) status = "Roll the dice!";
  } else if (pub.phase === "discard") {
    phaseText = "Waiting for discards…";
  } else if (pub.phase === "robber") {
    phaseText = `${name} is moving the robber`;
    if (myTurn()) status = "Pick a hex for the robber";
  } else if (pub.phase === "main") {
    phaseText = `${name}'s turn`;
    if (myTurn()) {
      status = armedBuild ? `Pick a spot for your ${armedBuild}` : "Build, trade, or end your turn";
    }
  } else if (pub.phase === "finished") {
    phaseText = `${seatName(pub.winner)} wins!`;
  }

  els.turnBanner.textContent = phaseText;
  els.statusStrip.textContent = status;
}

const DEV_COST = { ore: 1, wheat: 1, sheep: 1 };

function canAfford(cost) {
  if (!mine) return false;
  return Object.entries(cost).every(([res, n]) => mine.hand[res] >= n);
}

// Best maritime trade rate I can give for `res`, mirroring the server.
function bankRate(res) {
  let rate = 4;
  for (const port of (pub.ports || [])) {
    const onPort = port.vertices.some(v => {
      const occ = pub.occupied.vertices[v];
      return occ && occ.seat === mySeat;
    });
    if (!onPort) continue;
    if (port.type === res) rate = Math.min(rate, 2);
    else if (port.type === "3:1") rate = Math.min(rate, 3);
  }
  return rate;
}

function updateButtons() {
  const main = pub.phase === "main" && myTurn();
  els.diceTray.classList.toggle("active", pub.phase === "roll" && myTurn());
  els.buildRoad.disabled = !(main && canAfford(COSTS.road) && pub.pieces[mySeat].roads > 0);
  els.buildSettlement.disabled = !(main && canAfford(COSTS.settlement) && pub.pieces[mySeat].settlements > 0);
  els.buildCity.disabled = !(main && canAfford(COSTS.city) && pub.pieces[mySeat].cities > 0);
  els.buyDev.disabled = !(main && canAfford(DEV_COST));
  els.tradeBank.disabled = !(main && mine && RESOURCES.some(r => mine.hand[r] >= bankRate(r)));
  els.tradePlayers.disabled = !(main && mine && RESOURCES.some(r => mine.hand[r] > 0));
  els.endTurn.disabled = !main;

  for (const [btn, kind] of [[els.buildRoad, "road"], [els.buildSettlement, "settlement"], [els.buildCity, "city"]]) {
    btn.classList.toggle("armed", armedBuild === kind);
  }
}

// ---------------------------------------------------------------------------
// development card play flows
// ---------------------------------------------------------------------------

function playDevCard(card) {
  disarm();
  if (card === "knight") {
    knightPending = true;
    showToast("Knight: pick a hex to move the robber");
    updateTargets();
  } else if (card === "road") {
    devRoadEdges = [];
    showToast("Road Building: place two free roads");
    updateTargets();
  } else if (card === "plenty") {
    openResourcePicker("Year of Plenty", "Take any two resources from the bank.", 2, picks => {
      sendIntent("catan:playYearOfPlenty", { res1: picks[0], res2: picks[1] });
    });
  } else if (card === "monopoly") {
    openResourcePicker("Monopoly", "Name a resource — every other player hands you all of theirs.", 1, picks => {
      sendIntent("catan:playMonopoly", { resource: picks[0] });
    });
  }
}

// ---------------------------------------------------------------------------
// modals
// ---------------------------------------------------------------------------

function buildPicker(container, counts, max, onChange) {
  container.innerHTML = "";
  const picked = {};
  for (const res of RESOURCES) {
    picked[res] = 0;
    const cell = document.createElement("div");
    cell.className = "picker-cell";
    cell.innerHTML = `
      <div class="card card-${res}" style="width:38px;height:50px;font-size:1rem">${RESOURCE_ICONS[res]}</div>
      <span class="count" data-res="${res}">0</span>
      <div class="mini-btns">
        <button type="button" data-res="${res}" data-d="-1">−</button>
        <button type="button" data-res="${res}" data-d="1">+</button>
      </div>`;
    container.appendChild(cell);
  }
  container.onclick = (e) => {
    const btn = e.target.closest("button");
    if (!btn) return;
    const res = btn.getAttribute("data-res");
    const d = parseInt(btn.getAttribute("data-d"), 10);
    const total = Object.values(picked).reduce((a, b) => a + b, 0);
    if (d > 0 && (picked[res] >= counts[res] || total >= max)) return;
    if (d < 0 && picked[res] <= 0) return;
    picked[res] += d;
    container.querySelector(`.count[data-res="${res}"]`).textContent = picked[res];
    onChange(picked);
  };
  return picked;
}

function updateModals() {
  // Discard modal: shown when I owe cards.
  const owe = mine ? mine.discardPending : 0;
  if (pub.phase === "discard" && owe > 0) {
    if (els.discardModal.hidden) openDiscardModal(owe);
  } else {
    if (!els.discardModal.hidden) closeModal(els.discardModal);
  }

  if (pub.phase !== "robber") {
    if (!els.stealModal.hidden) closeModal(els.stealModal);
    pendingRobberHex = null;
  }

  if (pub.phase === "finished" && pub.winner !== null) {
    els.winnerTitle.textContent = `${seatName(pub.winner)} wins! 🏆`;
    els.winnerSub.textContent = pub.winner === mySeat
      ? "Congratulations, you settled Catan."
      : "Better luck next game.";
    // Reveal everyone's final VP (including hidden VP cards).
    if (pub.finalVP) {
      els.winnerScores.innerHTML = pub.seats.map((s, i) =>
        `<div class="score-row"><span class="player-swatch" style="background:${s.colour}"></span>${escapeHtml(s.name)}<b>${pub.finalVP[i]} VP</b></div>`).join("");
    }
    if (els.winnerModal.hidden) openModal(els.winnerModal, { dismissable: false });
  }
}

function openDiscardModal(owe) {
  els.discardPrompt.textContent = `You have more than 7 cards — discard ${owe}.`;
  let current = {};
  buildPicker(els.discardPicker, mine.hand, owe, picked => {
    current = picked;
    const total = Object.values(picked).reduce((a, b) => a + b, 0);
    els.discardConfirm.disabled = total !== owe;
  });
  els.discardConfirm.disabled = true;
  els.discardConfirm.onclick = () => {
    sendIntent("catan:discard", { resources: current });
    closeModal(els.discardModal);
  };
  openModal(els.discardModal, { dismissable: false });
}

function openTradeModal() {
  let give = null, receive = null;
  const renderRow = (container, label, eligible, onPick, selected) => {
    container.innerHTML = `<span style="align-self:center;font-weight:800">${label}</span>`;
    for (const res of RESOURCES) {
      const card = document.createElement("div");
      card.className = `card card-${res}`;
      card.style.cssText = "width:38px;height:50px;font-size:1rem;cursor:pointer";
      if (!eligible(res)) card.style.opacity = "0.3";
      if (selected === res) card.style.outline = "3px solid var(--c-accent)";
      card.innerHTML = `<span>${RESOURCE_ICONS[res]}</span>`;
      card.onclick = () => { if (eligible(res)) onPick(res); };
      container.appendChild(card);
    }
  };
  const refresh = () => {
    const rateLabel = give ? `Give ${bankRate(give)}` : "Give";
    renderRow(els.tradeGive, rateLabel, r => mine.hand[r] >= bankRate(r) && r !== receive, r => { give = r; refresh(); }, give);
    renderRow(els.tradeReceive, "Get 1", r => r !== give, r => { receive = r; refresh(); }, receive);
    const rateNote = document.getElementById("bank-trade-rate");
    if (rateNote) rateNote.textContent = give
      ? `Give ${bankRate(give)} ${RESOURCE_NAMES[give]}, receive one of your choice.`
      : "Ports lower your rate. Pick what to give, then what to receive.";
    els.tradeConfirm.disabled = !(give && receive);
  };
  refresh();
  els.tradeConfirm.onclick = () => {
    sendIntent("catan:bankTrade", { give, receive });
    closeModal(els.tradeModal);
  };
  els.tradeCancel.onclick = () => { closeModal(els.tradeModal); };
  openModal(els.tradeModal);
}

function openStealModal(victims, event = "catan:moveRobber") {
  els.stealOptions.innerHTML = "";
  for (const v of victims) {
    const btn = document.createElement("button");
    btn.className = "catan-btn";
    btn.innerHTML = `<span class="player-swatch" style="display:inline-block;background:${pub.seats[v].colour}"></span> ${escapeHtml(seatName(v))} (${pub.handCounts[v]} cards)`;
    btn.onclick = () => {
      sendIntent(event, { hex: pendingRobberHex, victimSeat: v });
      closeModal(els.stealModal);
      pendingRobberHex = null;
      knightPending = false;
    };
    els.stealOptions.appendChild(btn);
  }
  openModal(els.stealModal, { dismissable: false });
}

// Resource picker for Year of Plenty (count 2) and Monopoly (count 1).
function openResourcePicker(title, prompt, count, onConfirm) {
  els.resourceTitle.textContent = title;
  els.resourcePrompt.textContent = prompt;
  const picked = [];
  const render = () => {
    els.resourcePicker.innerHTML = "";
    for (const res of RESOURCES) {
      const n = picked.filter(p => p === res).length;
      const card = document.createElement("button");
      card.className = `card card-${res}`;
      card.style.cssText = "width:46px;height:60px;font-size:1.1rem;cursor:pointer;position:relative";
      card.innerHTML = `<span>${RESOURCE_ICONS[res]}</span>` + (n ? `<span class="card-count">×${n}</span>` : "");
      card.onclick = () => {
        if (picked.length >= count) picked.length = 0; // start over once full
        picked.push(res);
        if (picked.length > count) picked.shift();
        render();
        els.resourceConfirm.disabled = picked.length !== count;
      };
      els.resourcePicker.appendChild(card);
    }
  };
  render();
  els.resourceConfirm.disabled = true;
  els.resourceConfirm.onclick = () => {
    if (picked.length !== count) return;
    closeModal(els.resourceModal);
    onConfirm(picked.slice());
  };
  els.resourceCancel.onclick = () => { closeModal(els.resourceModal); };
  openModal(els.resourceModal);
}

// ---------------------------------------------------------------------------
// player-to-player trading
// ---------------------------------------------------------------------------

function openOfferModal() {
  const give = {}, get = {};
  let target = null; // null = anyone
  RESOURCES.forEach(r => { give[r] = 0; get[r] = 0; });

  const renderSide = (container, store, capByHand) => {
    container.innerHTML = "";
    for (const res of RESOURCES) {
      const cell = document.createElement("div");
      cell.className = "picker-cell";
      cell.innerHTML = `
        <div class="card card-${res}" style="width:34px;height:46px;font-size:0.95rem">${RESOURCE_ICONS[res]}</div>
        <span class="count">${store[res]}</span>
        <div class="mini-btns">
          <button type="button" data-d="-1">−</button>
          <button type="button" data-d="1">+</button>
        </div>`;
      cell.querySelector('[data-d="1"]').onclick = () => {
        if (capByHand && store[res] >= mine.hand[res]) return;
        store[res]++; refresh();
      };
      cell.querySelector('[data-d="-1"]').onclick = () => { if (store[res] > 0) { store[res]--; refresh(); } };
      container.appendChild(cell);
    }
  };
  const renderTarget = () => {
    els.offerTarget.innerHTML = '<span class="trade-side-label">With</span>';
    const mk = (label, val) => {
      const b = document.createElement("button");
      b.className = "catan-btn" + (target === val ? " armed" : "");
      b.textContent = label;
      b.onclick = () => { target = val; renderTarget(); };
      els.offerTarget.appendChild(b);
    };
    mk("Anyone", null);
    pub.seats.forEach((s, i) => { if (i !== mySeat) mk(s.name, i); });
  };
  const sum = o => Object.values(o).reduce((a, b) => a + b, 0);
  const refresh = () => {
    renderSide(els.offerGive, give, true);
    renderSide(els.offerGet, get, false);
    els.offerSend.disabled = !(sum(give) > 0 && sum(get) > 0);
  };
  refresh();
  renderTarget();
  els.offerSend.onclick = () => {
    const clean = o => Object.fromEntries(Object.entries(o).filter(([, n]) => n > 0));
    sendIntent("catan:proposeTrade", { give: clean(give), get: clean(get), to: target });
    closeModal(els.offerModal);
  };
  els.offerCancel.onclick = () => { closeModal(els.offerModal); };
  openModal(els.offerModal);
}

function describeBundle(b) {
  return Object.entries(b).map(([r, n]) => `${n}${RESOURCE_ICONS[r]}`).join(" ") || "nothing";
}

// Show/refresh the incoming-offer modal for a live trade I can respond to.
function updateIncomingTrade() {
  const t = pub.trade;
  const iAmTarget = t && mine && t.from !== mySeat && (t.to === null || t.to === mySeat);
  if (!iAmTarget) { if (!els.incomingModal.hidden) closeModal(els.incomingModal); return; }
  const key = JSON.stringify(t);
  if (key === dismissedTradeKey) { if (!els.incomingModal.hidden) closeModal(els.incomingModal); return; }
  els.incomingTitle.textContent = `${seatName(t.from)} offers a trade`;
  const haveIt = Object.entries(t.get).every(([r, n]) => mine.hand[r] >= n);
  els.incomingBody.innerHTML =
    `<p>They give <b>${describeBundle(t.give)}</b></p>` +
    `<p>They want <b>${describeBundle(t.get)}</b> from you</p>` +
    (haveIt ? "" : `<p class="trade-warn">You don't have what they want.</p>`);
  els.incomingAccept.disabled = !haveIt;
  els.incomingAccept.onclick = () => {
    sendIntent("catan:respondTrade", { accept: true });
    closeModal(els.incomingModal);
  };
  els.incomingDecline.onclick = () => {
    sendIntent("catan:respondTrade", { accept: false });
    dismissedTradeKey = JSON.stringify(t);
    closeModal(els.incomingModal);
  };
  if (els.incomingModal.hidden) openModal(els.incomingModal);
}

// ---------------------------------------------------------------------------
// misc
// ---------------------------------------------------------------------------

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, c => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
  }[c]));
}

let toastTimer = null;
function showToast(message) {
  els.statusStrip.textContent = message;
  els.statusStrip.style.background = "var(--c-highlight)";
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => {
    els.statusStrip.style.background = "";
    renderBanner();
  }, 2500);
}

// ---------------------------------------------------------------------------
// wire buttons + boot
// ---------------------------------------------------------------------------

// Dice tray: press and hold to shake, release to throw.
let diceHolding = false;
function diceCanRoll() { return pub && pub.phase === "roll" && myTurn(); }
function startShake(e) {
  if (!diceCanRoll()) return;
  e.preventDefault();
  diceHolding = true;
  els.dicePair.classList.add("shaking");
  els.diceHint.textContent = "Release to throw!";
}
function throwDice() {
  els.dicePair.classList.remove("shaking");
  if (!diceHolding) return;
  diceHolding = false;
  els.diceHint.textContent = "Hold to roll";
  if (diceCanRoll()) sendIntent("catan:roll");
}
els.diceTray.addEventListener("pointerdown", startShake);
els.diceTray.addEventListener("pointerup", throwDice);
els.diceTray.addEventListener("pointerleave", () => { if (diceHolding) throwDice(); });
els.diceTray.addEventListener("keydown", e => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); if (diceCanRoll()) sendIntent("catan:roll"); } });

els.endTurn.addEventListener("click", () => { disarm(); sendIntent("catan:endTurn"); });
els.buildRoad.addEventListener("click", () => armBuild("road"));
els.buildSettlement.addEventListener("click", () => armBuild("settlement"));
els.buildCity.addEventListener("click", () => armBuild("city"));
els.buyDev.addEventListener("click", () => { disarm(); sendIntent("catan:buyDev"); });
els.tradeBank.addEventListener("click", openTradeModal);
els.tradePlayers.addEventListener("click", openOfferModal);

function refreshSoundToggle() {
  els.soundToggle.textContent = isMuted() ? "🔇" : "🔊";
  els.soundToggle.setAttribute("aria-pressed", String(!isMuted()));
}
els.soundToggle.addEventListener("click", () => { setMuted(!isMuted()); refreshSoundToggle(); });
refreshSoundToggle();

if (FIXTURE_MODE) {
  import("./fixture.js").then(({ fixturePublic, fixturePrivate }) => {
    mySeat = fixturePrivate.seat;
    applyState(fixturePublic, fixturePrivate);
  });
} else if (!roomCode) {
  window.location.href = "./home.html";
} else {
  connect();
}
